[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/go-chi/chi"
  version = "3.3.2"

[[constraint]]
  name = "github.com/astaxie/beego"
  version = "1.9.2"
  
[[constraint]]
  name = "github.com/go-sql-driver/mysql"
  version = "1.3.0"